name: e2e Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: install dependencies
      run: npm i --force

    - name: start db container and migrate database
      run: npm run db:test:restart

    - name: Run tests
      run: npm run test:e2e

    - name: Stop containers
      if: always()
      run: docker-compose down --remove-orphans 
